### ISSUE TITLE
Clock doesn't change to DST

### ISSUE THREAD

**Issue by christianerbsmehl** [N1cls/Wordclock#14]
I built the WordClock from Printables and everything worked great in the first place. But then summer came and my clock didn't switch to daylight saving time :( Sure, soon it will be correct again, but not using the clock in summer or keeping in mind to add an hour doesn't seem like a good solution to me ;) 

Any ideas what I could try?

I'm using the default settings for time server and timezone (`de.pool.ntp.org`, `CET-1CEST,M3.5.0/02,M10.5.0/03`). I'm also using an RTC module.

**Comment by AWSW-de** [comment]
Hello,
must be a bug then in the RTC module code section. I had many small issues with these RTC modules and therefore did not use them anymore. Without the RTC module the time is taken from the internet every hour and then it worked fine in the last years. I guess you may correct this by a restart. Otherwise I don’t see a good and easy way to correct this because this was some standard code. Because you are the first one I remember having an issue with this offset it could also be that the RTC battery is dead or the module has a problem itself….
Try to doable the RTC usage by  hanging the settings value„int useRTC = 1;“ to „0“. That should do the updates properly. 
Kind regards and enjoy your WordClock. =)

**Comment by christianerbsmehl** [comment]
Thanks for your reply. I removed the RTC module and everything works now.
