### ISSUE TITLE
I got this built in english

### ISSUE THREAD

**Issue by rchadgray** [N1cls/Wordclock#5]
There is some bad English.  Great project though.

I wrote down the phrases used currently and the proper English.  I think everything is there on the 3D print except TIL or 'TIL  (this is short for the word UNTIL).

Maybe the letters FTO on line 4 can become TIL or line 5 ERU become TIL

It is Nine OClock

It is five past nine

It is ten past nine

It is quarter past nine   -> "It is a quarter past nine"

It is twenty past nine

It is five half to ten     ->  "It is twentyfive past nine"

It is half ten             ->  "It is half past nine"

It is five half past ten   ->  "It is twentyfive 'til ten"

It is twenty to ten        ->  "It is twenty 'til ten"

it is quarter to ten       ->  "it is a quarter 'til ten"

it is ten to ten           ->  "it is ten 'til ten"

it is five to ten          ->  "it is five 'til ten"

**Comment by AWSW-de** [comment]
Hello,
thanks for your feedback and i will update this according to your suggestions.
Because there is not the word "til" i would try to use the existing word "to" instead.
The wired thing is that i was thinking about this yesterday too and to me this sounds strange, because we use it the now implemented way in german language... 

Thanks a lot again and i will post again here when the update is ready...

Kind regards

**Comment by AWSW-de** [comment]
Hello @rchadgray ,
updated the code to "V5.7" which should get the english texts better. I used the word TO because the layout is fixed in plastic alreday...

@N1cls: We should keep this in mind for an updated version to add the word 'TIL then to the layout.

Thanks again and Merry Christmas in advance.

Kind Regards
AWSW

**Comment by N1cls** [comment]
Thank you AWSW for the fast response! I’ll have that in mind for the next Hardware Upgrade! Cheers and merry Christmas N1cls On 21. Dec 2022, at 11:23, AWSW-de ***@***.***> wrote:﻿
Hello @rchadgray ,
updated the code to "V5.7" which should get the english texts better. I used the word TO because the layout is fixed in plastic alreday...
@N1cls: We should keep this in mind for an updated version to add the word 'TIL then to the layout.
Thanks again and Merry Christmas in advance.
Kind Regards
AWSW

**Comment by rchadgray** [comment]
Great Fix!  I will let it run.

I appreciate that the settings were stored in NV.  I did not have to setup the preferences again when i uploaded the new code.

Chad

I will follow up on Printables with pictures.

**Comment by rchadgray** [comment]
One idea i try to do for Arduino projects is supply a "portable" folder that has the preferences, libraries and board manager.  Setup for the user.  It reduces support questions on how to setup the arduino IDE.  The only downside is the portable folder can get into many gigabytes, but most people can download that now.

https://docs.arduino.cc/software/ide-v1/tutorials/PortableIDE

**Comment by AWSW-de** [comment]
Hi, 
glad you like it. 

Thanks for the hint. I will have a look into it. Sounds interesting.

Merry Christmas and much fun with the WordClock.

Kind Regards
